apiVersion: v1
kind: ReplicationController
metadata:
  name: facedetect-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
         name: payaramicro
 spec:
      containers:
       - name: facedetect
        image: yoshio.azurecr.io/tyoshio2002/facedetect:1.0
        ports:
          - containerPort: 8080
  imagePullSecrets:
    - name: regsecret

